/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_12092024;

import javax.swing.SwingUtilities;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_inicar = new javax.swing.JButton();
        btn_pausar = new javax.swing.JButton();
        btn_continuar = new javax.swing.JButton();
        btn_parar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jpb_progreso = new javax.swing.JProgressBar();
        btn_aumentarMaualmente = new javax.swing.JButton();
        lbl_progreso = new javax.swing.JLabel();
        btn_disminuirManualmente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_inicar.setText("iniciar");
        btn_inicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_inicarMouseClicked(evt);
            }
        });

        btn_pausar.setText("Pausar");
        btn_pausar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pausarMouseClicked(evt);
            }
        });

        btn_continuar.setText("Continuar");
        btn_continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_continuarMouseClicked(evt);
            }
        });

        btn_parar.setText("Parar");
        btn_parar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pararMouseClicked(evt);
            }
        });

        jLabel1.setText("Progreso");

        jpb_progreso.setBackground(new java.awt.Color(204, 255, 204));
        jpb_progreso.setToolTipText("");

        btn_aumentarMaualmente.setText("Aumentar manualmente");
        btn_aumentarMaualmente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aumentarMaualmenteMouseClicked(evt);
            }
        });
        btn_aumentarMaualmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aumentarMaualmenteActionPerformed(evt);
            }
        });

        lbl_progreso.setText("0%");

        btn_disminuirManualmente.setText("Aumentar manualmente");
        btn_disminuirManualmente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_disminuirManualmenteMouseClicked(evt);
            }
        });
        btn_disminuirManualmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_disminuirManualmenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpb_progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_inicar)
                                .addGap(35, 35, 35)
                                .addComponent(btn_pausar)
                                .addGap(43, 43, 43)
                                .addComponent(btn_continuar)
                                .addGap(57, 57, 57)
                                .addComponent(btn_parar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(lbl_progreso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btn_aumentarMaualmente)
                        .addGap(44, 44, 44)
                        .addComponent(btn_disminuirManualmente)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jpb_progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_progreso)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aumentarMaualmente)
                    .addComponent(btn_disminuirManualmente))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inicar)
                    .addComponent(btn_pausar)
                    .addComponent(btn_continuar)
                    .addComponent(btn_parar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aumentarMaualmenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aumentarMaualmenteMouseClicked
        valorActualProgressbar++;
lbl_progreso.setText(valorActualProgressbar+"%");
      jpb_progreso.setValue(valorActualProgressbar);
        
    }//GEN-LAST:event_btn_aumentarMaualmenteMouseClicked

    private void btn_aumentarMaualmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aumentarMaualmenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aumentarMaualmenteActionPerformed

    private void btn_disminuirManualmenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_disminuirManualmenteMouseClicked
        valorActualProgressbar--;
        lbl_progreso.setText(valorActualProgressbar+"%");
      jpb_progreso.setValue(valorActualProgressbar);
    }//GEN-LAST:event_btn_disminuirManualmenteMouseClicked

    private void btn_disminuirManualmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_disminuirManualmenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_disminuirManualmenteActionPerformed
    private void actualizar(int val ){
         lbl_progreso.setText(val+"%");
          jpb_progreso.setValue(val);
    }
    private void btn_inicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicarMouseClicked
        Thread hiloActualizarProgressBar = new Thread(() ->{
        // codigo que queremos que el hilo ejecute 
        // podemos llamar metodos dentro del hilo
            int progreso=0;
            while (progreso <= 100 && !isStopped) {//mientras stop=false y el contador sea menor a 100, vamos a seguir ejecutando el codigo
                if (isPausado) {
                    //esta en pausa
                    try {
                        Thread.sleep(300); //el slee se trabaja con mili segundo
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                } else {
                    // el programa no esta pausado
                    int progresoLocal = progreso;
                    progreso++;
                    // ejecutar en el EDT para que las actualizaciones no choquen o causen errores
                    SwingUtilities.invokeLater(() -> actualizar(progresoLocal));
                    //Sleep -> decirle al hilo que tome un descanso para que la actualizacion del progress bar no sea tan rapido
                    try {
                        Thread.sleep(300); //el slee se trabaja con mili segundo
                    } catch (Exception e) {
                        System.out.println(e);
                    }

                }
            }

            if (isStopped) {
                lbl_progreso.setText("0%");
                jpb_progreso.setValue(0);
                isStopped = false;
            }
        });
        
        //iniciar el hilo, sin esto el codigo que pusimos dentro NO se ejecutara
        hiloActualizarProgressBar.start();
    }//GEN-LAST:event_btn_inicarMouseClicked

    private void btn_pausarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pausarMouseClicked
        // TODO add your handling code here:
        isPausado = true;
    }//GEN-LAST:event_btn_pausarMouseClicked

    private void btn_continuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_continuarMouseClicked
        // TODO add your handling code here:
        isPausado=false;
    }//GEN-LAST:event_btn_continuarMouseClicked

    private void btn_pararMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pararMouseClicked
        // TODO add your handling code here:
        isStopped = true;
    }//GEN-LAST:event_btn_pararMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    int valorActualProgressbar = 0;
    boolean isPausado=false;
    boolean isStopped=false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aumentarMaualmente;
    private javax.swing.JButton btn_continuar;
    private javax.swing.JButton btn_disminuirManualmente;
    private javax.swing.JButton btn_inicar;
    private javax.swing.JButton btn_parar;
    private javax.swing.JButton btn_pausar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jpb_progreso;
    private javax.swing.JLabel lbl_progreso;
    // End of variables declaration//GEN-END:variables
}
