/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_02092024;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_DialogPrincipal = new javax.swing.JDialog();
        lbl_mensajedialog = new javax.swing.JLabel();
        lbl_mensajeDialog = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jpm_popMenuOpciones = new javax.swing.JPopupMenu();
        jmi_color = new javax.swing.JMenuItem();
        jmi_limpiar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btn_mostrarDialog = new javax.swing.JButton();
        txt_mensaje = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_etiquetaPopUpMenu = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txt_textoEtiqueta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_cargarArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_archivo = new javax.swing.JTextArea();
        btn_guardarArchivo = new javax.swing.JButton();

        lbl_mensajedialog.setText("Hola Mundo!");

        jButton1.setText("Limpiar Texto");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setText("DIALOG");

        javax.swing.GroupLayout jd_DialogPrincipalLayout = new javax.swing.GroupLayout(jd_DialogPrincipal.getContentPane());
        jd_DialogPrincipal.getContentPane().setLayout(jd_DialogPrincipalLayout);
        jd_DialogPrincipalLayout.setHorizontalGroup(
            jd_DialogPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DialogPrincipalLayout.createSequentialGroup()
                .addGroup(jd_DialogPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_DialogPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel2))
                    .addGroup(jd_DialogPrincipalLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(jd_DialogPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_mensajedialog)
                            .addGroup(jd_DialogPrincipalLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(lbl_mensajeDialog))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jd_DialogPrincipalLayout.setVerticalGroup(
            jd_DialogPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DialogPrincipalLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(lbl_mensajedialog)
                .addGap(136, 136, 136)
                .addComponent(lbl_mensajeDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(99, 99, 99))
        );

        jmi_color.setText("Cambiar Color");
        jpm_popMenuOpciones.add(jmi_color);

        jmi_limpiar.setText("Limpiar Label");
        jmi_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_limpiarMouseClicked(evt);
            }
        });
        jmi_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_limpiarActionPerformed(evt);
            }
        });
        jpm_popMenuOpciones.add(jmi_limpiar);

        jMenu1.setText("Mostrar");

        jMenuItem1.setText("Mostrar Dialog");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jpm_popMenuOpciones.add(jMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_mostrarDialog.setText("Mostrar Dialog!");
        btn_mostrarDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrarDialogMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mostrarDialogMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btn_mostrarDialog))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_mostrarDialog)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dialogs", jPanel1);

        lbl_etiquetaPopUpMenu.setBackground(new java.awt.Color(204, 255, 204));
        lbl_etiquetaPopUpMenu.setForeground(new java.awt.Color(255, 0, 0));
        lbl_etiquetaPopUpMenu.setText("EditarTexto");
        lbl_etiquetaPopUpMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_etiquetaPopUpMenuMouseClicked(evt);
            }
        });

        jButton2.setText("CambiarTexto");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        txt_textoEtiqueta.setText("jTextField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(txt_textoEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_etiquetaPopUpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_etiquetaPopUpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(txt_textoEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pop up Menus", jPanel2);

        btn_cargarArchivo.setText("Cargar Archivo");
        btn_cargarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cargarArchivoMouseClicked(evt);
            }
        });

        jta_archivo.setColumns(20);
        jta_archivo.setRows(5);
        jScrollPane1.setViewportView(jta_archivo);

        btn_guardarArchivo.setText("Guardar Archivo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cargarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_guardarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btn_cargarArchivo)
                        .addGap(48, 48, 48)
                        .addComponent(btn_guardarArchivo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Archivos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrarDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarDialogMouseClicked
        jd_DialogPrincipal.setVisible(true);
        String mensaje = txt_mensaje.getText();
        lbl_mensajedialog.setText(mensaje);
//        jd_DialogPrincipal.setVisible(false); cierra/ oculta el dialog
    }//GEN-LAST:event_btn_mostrarDialogMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        txt_mensaje.setText("");
     
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        lbl_etiquetaPopUpMenu.setText(txt_textoEtiqueta.getText());
    }//GEN-LAST:event_jButton2MouseClicked

    private void lbl_etiquetaPopUpMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_etiquetaPopUpMenuMouseClicked
        // INVOKER, x, y 
        
        if(evt.getButton() == 3){
//    if(evt.isPopupTrigger()){ //usarse con mouse pressed
             jpm_popMenuOpciones.show(lbl_etiquetaPopUpMenu,evt.getX() ,evt.getY());
        }else{
            System.out.println("No es click derecho");
        }
       
        
    }//GEN-LAST:event_lbl_etiquetaPopUpMenuMouseClicked

    private void btn_mostrarDialogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarDialogMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mostrarDialogMouseExited

    private void jmi_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_limpiarMouseClicked
     
    }//GEN-LAST:event_jmi_limpiarMouseClicked

    private void jmi_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_limpiarActionPerformed
           System.out.println("Hola mundo");
        lbl_etiquetaPopUpMenu.setText("");
     txt_textoEtiqueta.setText("");
    }//GEN-LAST:event_jmi_limpiarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jd_DialogPrincipal.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_cargarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cargarArchivoMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int state = fileChooser.showOpenDialog(this);
        
        if(state == JFileChooser.APPROVE_OPTION){
            File seleccionado = fileChooser.getSelectedFile();
            System.out.println("RUTAS DEL ARCHIVO SELECCIONADO");
            System.out.println(seleccionado.getName()); //nombre del archivo
            System.out.println(seleccionado.getAbsolutePath()); // ruta absooluta / estatica 
            System.out.println(seleccionado.getPath()); // regresala ruta relativa 
            
            try{
                BufferedReader br = new BufferedReader(new FileReader(seleccionado)); 
                String linea;
                jta_archivo.setText("");
                do {
                    linea = br.readLine();// va leyendo 
//                    System.out.println(linea);
                    if(linea!=null){
                       jta_archivo.append(linea+"\n");
                    }
                } while (linea!=null);
            }catch(IOException e){
                
            }
        }else{
            System.out.println("No hay archivos para trabajar");
        }
    }//GEN-LAST:event_btn_cargarArchivoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    ArrayList<String> l = new ArrayList<String>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cargarArchivo;
    private javax.swing.JButton btn_guardarArchivo;
    private javax.swing.JButton btn_mostrarDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_DialogPrincipal;
    private javax.swing.JMenuItem jmi_color;
    private javax.swing.JMenuItem jmi_limpiar;
    private javax.swing.JPopupMenu jpm_popMenuOpciones;
    private javax.swing.JTextArea jta_archivo;
    private javax.swing.JLabel lbl_etiquetaPopUpMenu;
    private javax.swing.JLabel lbl_mensajeDialog;
    private javax.swing.JLabel lbl_mensajedialog;
    private javax.swing.JTextField txt_mensaje;
    private javax.swing.JTextField txt_textoEtiqueta;
    // End of variables declaration//GEN-END:variables
}
