/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_20082024;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_examenCanvas = new javax.swing.JPanel();
        lbl_textoTab1 = new javax.swing.JLabel();
        jrb_for = new javax.swing.JRadioButton();
        jrb_while = new javax.swing.JRadioButton();
        jrb_todasLasAnteriorires = new javax.swing.JRadioButton();
        jcb_aceptoTerminosCondiciones = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_justifiquerespuesta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lbl_descripcionExamen = new javax.swing.JLabel();
        jp_miniWord = new javax.swing.JPanel();
        lbl_tamanoLetra = new javax.swing.JLabel();
        lbl_tipoLetra = new javax.swing.JLabel();
        lbl_estiloLetra = new javax.swing.JLabel();
        lbl_colorLetra = new javax.swing.JLabel();
        lbl_coloBackground = new javax.swing.JLabel();
        txt_tamanoLetra = new javax.swing.JTextField();
        txt_tipoLetra = new javax.swing.JTextField();
        jcb_estiloLetra = new javax.swing.JComboBox<>();
        btnColorBackground = new javax.swing.JButton();
        btnColorLetra = new javax.swing.JButton();
        txt_contenido = new javax.swing.JTextField();
        lbl_ingreseTexto = new javax.swing.JLabel();
        btn_actualizarSize = new javax.swing.JButton();
        btn_actualizarFont = new javax.swing.JButton();
        jp_listar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jmb_menuPrincipal = new javax.swing.JMenuBar();
        jmi_archivo = new javax.swing.JMenu();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_abrir = new javax.swing.JMenuItem();
        jmi_evaluar = new javax.swing.JMenuItem();
        jmi_limpiarpantalla = new javax.swing.JMenuItem();
        jmi_exportar = new javax.swing.JMenu();
        jmi_exportarpdf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        lbl_textoTab1.setText("Es un bucle");

        jrb_for.setText("For");
        jrb_for.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_forMouseClicked(evt);
            }
        });
        jrb_for.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_forActionPerformed(evt);
            }
        });

        jrb_while.setText("While");
        jrb_while.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_whileMouseClicked(evt);
            }
        });

        jrb_todasLasAnteriorires.setText("Todas las anteriores");
        jrb_todasLasAnteriorires.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_todasLasAnterioriresMouseClicked(evt);
            }
        });
        jrb_todasLasAnteriorires.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_todasLasAnterioriresActionPerformed(evt);
            }
        });

        jcb_aceptoTerminosCondiciones.setText("Acepto los terminos y condiciones");
        jcb_aceptoTerminosCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_aceptoTerminosCondicionesActionPerformed(evt);
            }
        });

        txt_justifiquerespuesta.setColumns(20);
        txt_justifiquerespuesta.setRows(5);
        jScrollPane1.setViewportView(txt_justifiquerespuesta);

        jLabel1.setText("Justifique su Respuesta:");

        lbl_descripcionExamen.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jp_examenCanvasLayout = new javax.swing.GroupLayout(jp_examenCanvas);
        jp_examenCanvas.setLayout(jp_examenCanvasLayout);
        jp_examenCanvasLayout.setHorizontalGroup(
            jp_examenCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_examenCanvasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jp_examenCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_examenCanvasLayout.createSequentialGroup()
                        .addGroup(jp_examenCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_aceptoTerminosCondiciones)
                            .addComponent(jrb_while)
                            .addComponent(jrb_todasLasAnteriorires)
                            .addComponent(jrb_for))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jp_examenCanvasLayout.createSequentialGroup()
                        .addComponent(lbl_textoTab1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(224, 224, 224))))
            .addGroup(jp_examenCanvasLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(lbl_descripcionExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_examenCanvasLayout.setVerticalGroup(
            jp_examenCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_examenCanvasLayout.createSequentialGroup()
                .addGroup(jp_examenCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_examenCanvasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbl_textoTab1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_examenCanvasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGroup(jp_examenCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_examenCanvasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jrb_for)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_while)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_todasLasAnteriorires)
                        .addGap(50, 50, 50)
                        .addComponent(jcb_aceptoTerminosCondiciones))
                    .addGroup(jp_examenCanvasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(lbl_descripcionExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Canvas", jp_examenCanvas);

        lbl_tamanoLetra.setText("Tamaño");

        lbl_tipoLetra.setText("Tipo de letra");

        lbl_estiloLetra.setText("Estilo de letra");

        lbl_colorLetra.setText("Color de letra");

        lbl_coloBackground.setText("Color background");

        jcb_estiloLetra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negrita", "Italica", "Regular" }));
        jcb_estiloLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_estiloLetraActionPerformed(evt);
            }
        });

        btnColorBackground.setIcon(new javax.swing.ImageIcon("/Users/claudiacortes/Downloads/color-palette.png")); // NOI18N
        btnColorBackground.setText(" Background");
        btnColorBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorBackgroundMouseClicked(evt);
            }
        });

        btnColorLetra.setIcon(new javax.swing.ImageIcon("/Users/claudiacortes/Downloads/colored-pencils.png")); // NOI18N
        btnColorLetra.setText(" Foreground");
        btnColorLetra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorLetraMouseClicked(evt);
            }
        });

        lbl_ingreseTexto.setText("Ingrese su texto");

        btn_actualizarSize.setText("actualizar");
        btn_actualizarSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarSizeMouseClicked(evt);
            }
        });

        btn_actualizarFont.setText("actualizar");
        btn_actualizarFont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarFontMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_miniWordLayout = new javax.swing.GroupLayout(jp_miniWord);
        jp_miniWord.setLayout(jp_miniWordLayout);
        jp_miniWordLayout.setHorizontalGroup(
            jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_miniWordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
            .addGroup(jp_miniWordLayout.createSequentialGroup()
                .addGroup(jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_miniWordLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_miniWordLayout.createSequentialGroup()
                                .addGroup(jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jp_miniWordLayout.createSequentialGroup()
                                        .addComponent(lbl_tipoLetra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_tipoLetra))
                                    .addGroup(jp_miniWordLayout.createSequentialGroup()
                                        .addComponent(lbl_tamanoLetra)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_tamanoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_actualizarSize)
                                    .addComponent(btn_actualizarFont))
                                .addGap(52, 52, 52)
                                .addGroup(jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jp_miniWordLayout.createSequentialGroup()
                                        .addComponent(lbl_colorLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnColorLetra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jp_miniWordLayout.createSequentialGroup()
                                        .addComponent(lbl_coloBackground)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnColorBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                            .addGroup(jp_miniWordLayout.createSequentialGroup()
                                .addComponent(lbl_estiloLetra)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_estiloLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_miniWordLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(lbl_ingreseTexto)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jp_miniWordLayout.setVerticalGroup(
            jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_miniWordLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tamanoLetra)
                    .addComponent(lbl_colorLetra)
                    .addComponent(txt_tamanoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColorLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizarSize))
                .addGroup(jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_miniWordLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tipoLetra)
                            .addComponent(txt_tipoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_actualizarFont)))
                    .addGroup(jp_miniWordLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_coloBackground)
                            .addComponent(btnColorBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jp_miniWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_estiloLetra)
                    .addComponent(jcb_estiloLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lbl_ingreseTexto)
                .addGap(18, 18, 18)
                .addComponent(txt_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Word", jp_miniWord);

        jLabel3.setText("Etiqueta en el tab 3");

        javax.swing.GroupLayout jp_listarLayout = new javax.swing.GroupLayout(jp_listar);
        jp_listar.setLayout(jp_listarLayout);
        jp_listarLayout.setHorizontalGroup(
            jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(663, Short.MAX_VALUE))
        );
        jp_listarLayout.setVerticalGroup(
            jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jp_listar);

        jmi_archivo.setText("Archivo");

        jmi_guardar.setText("Guardar");
        jmi_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_guardarMouseClicked(evt);
            }
        });
        jmi_archivo.add(jmi_guardar);

        jmi_abrir.setText("Abrir");
        jmi_abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_abrirMouseClicked(evt);
            }
        });
        jmi_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_abrirActionPerformed(evt);
            }
        });
        jmi_archivo.add(jmi_abrir);

        jmi_evaluar.setText("Evaluar");
        jmi_evaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_evaluarActionPerformed(evt);
            }
        });
        jmi_archivo.add(jmi_evaluar);

        jmi_limpiarpantalla.setText("Limpiar");
        jmi_limpiarpantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_limpiarpantallaActionPerformed(evt);
            }
        });
        jmi_archivo.add(jmi_limpiarpantalla);

        jmb_menuPrincipal.add(jmi_archivo);

        jmi_exportar.setText("Exportar");

        jmi_exportarpdf.setText("PDF");
        jmi_exportar.add(jmi_exportarpdf);

        jmb_menuPrincipal.add(jmi_exportar);

        setJMenuBar(jmb_menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
//       lbl_textoTab1.setText("Hola Mundo!, diste click en la tab#1");
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jrb_forActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_forActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_forActionPerformed

    private void jcb_aceptoTerminosCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_aceptoTerminosCondicionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_aceptoTerminosCondicionesActionPerformed

    private void jmi_evaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_evaluarActionPerformed
  
        if (jcb_aceptoTerminosCondiciones.isSelected()) {
            if (jrb_todasLasAnteriorires.isSelected() && txt_justifiquerespuesta.getText().length() >= 20) {
             lbl_descripcionExamen.setText("Aprobado!");
            } else {
                lbl_descripcionExamen.setText("Reprobado :(");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Acepte los terminos y condiciones primero");
        }

    }//GEN-LAST:event_jmi_evaluarActionPerformed

    private void jmi_abrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_abrirMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jmi_abrirMouseClicked

    private void jmi_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_guardarMouseClicked
        // TODO add your handling code here:
        System.out.println("Simulando que guardamos un archivo......");
    }//GEN-LAST:event_jmi_guardarMouseClicked

    private void jmi_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_abrirActionPerformed
        // TODO add your handling code here:
               System.out.println("Simulando que abrimos un archivos... desde action .");
    }//GEN-LAST:event_jmi_abrirActionPerformed

    private void jmi_limpiarpantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_limpiarpantallaActionPerformed
        // TODO add your handling code here:
        txt_justifiquerespuesta.setText("");
     
    }//GEN-LAST:event_jmi_limpiarpantallaActionPerformed

    private void jrb_forMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_forMouseClicked
        jrb_todasLasAnteriorires.setSelected(false);
        jrb_while.setSelected(false);
        //modifica la propiedad selected
    }//GEN-LAST:event_jrb_forMouseClicked

    private void jrb_whileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_whileMouseClicked
        jrb_todasLasAnteriorires.setSelected(false);
        jrb_for.setSelected(false);
    }//GEN-LAST:event_jrb_whileMouseClicked

    private void jrb_todasLasAnterioriresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_todasLasAnterioriresMouseClicked
        jrb_for.setSelected(false);
        jrb_while.setSelected(false);
    }//GEN-LAST:event_jrb_todasLasAnterioriresMouseClicked

    private void jrb_todasLasAnterioriresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_todasLasAnterioriresActionPerformed
        jrb_for.setSelected(false);
        jrb_while.setSelected(false);
    }//GEN-LAST:event_jrb_todasLasAnterioriresActionPerformed

    private void btnColorLetraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorLetraMouseClicked
        JColorChooser pantallaSeleccionColor = new JColorChooser();
//        pantallaSeleccionColor.setVisible(true);
   
        Color colorLetra= pantallaSeleccionColor.showDialog(this,"Seleccione el color que desea", Color.red);
        txt_contenido.setForeground(colorLetra);
        //foreground -> color de la letra 
       
        
    }//GEN-LAST:event_btnColorLetraMouseClicked

    private void btnColorBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorBackgroundMouseClicked
             JColorChooser pantallaSeleccionColor = new JColorChooser();
//        pantallaSeleccionColor.setVisible(true);
        Color colorBackground= pantallaSeleccionColor.showDialog(this,"Seleccione el color que desea", Color.red);
        txt_contenido.setBackground(colorBackground);
        //backgrund -> color del fondo
    }//GEN-LAST:event_btnColorBackgroundMouseClicked

    private void btn_actualizarSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarSizeMouseClicked
             /*
       Jtextfield(){
        private String text ="";
       private  Color foreground;
       private Color background ;
       private Font font;
        ......
        
       }
       */
//        Font fuenteActual = txt_contenido.getFont();
           
        // forma 1: Crear una nueva font y actualizarla en el textField
                                    // tipo de letra , estilo(enum) , tamano
   
        int size = Integer.parseInt(txt_tamanoLetra.getText());
        Font fuenteVieja= txt_contenido.getFont();
         int estilo = fuenteVieja.getStyle();
         String fuente = fuenteVieja.getFontName();
        Font nuevaFuente = new Font(fuente,estilo,size);
         txt_contenido.setFont(nuevaFuente);
 
    }//GEN-LAST:event_btn_actualizarSizeMouseClicked

    private void btn_actualizarFontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarFontMouseClicked
        String nombreFuente = txt_tipoLetra.getText();
        Font fuenteVieja= txt_contenido.getFont();
        int estilo = fuenteVieja.getStyle(); // regresa el tilo (bold, italic, plain)
        int size = fuenteVieja.getSize();
        Font nuevaFuente = new Font(nombreFuente,estilo,size);
         txt_contenido.setFont(nuevaFuente);
         
    }//GEN-LAST:event_btn_actualizarFontMouseClicked

    private void jcb_estiloLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_estiloLetraActionPerformed
         String nombreFuente = txt_tipoLetra.getText();
         String estilo = jcb_estiloLetra.getSelectedItem().toString();
         Font fuenteVieja= txt_contenido.getFont();
         String fuente = fuenteVieja.getFontName();
         int size = fuenteVieja.getSize();
        Font nuevaFuente ;
        if (estilo.equalsIgnoreCase("Negrita")) {
            nuevaFuente= new Font(fuente,Font.BOLD,size);
        } else if (estilo.equalsIgnoreCase("Italica")) {
             nuevaFuente= new Font(fuente,Font.ITALIC,size);
        } else {
         nuevaFuente= new Font(fuente,Font.PLAIN,size);
        }
        txt_contenido.setFont(nuevaFuente);
    }//GEN-LAST:event_jcb_estiloLetraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColorBackground;
    private javax.swing.JButton btnColorLetra;
    private javax.swing.JButton btn_actualizarFont;
    private javax.swing.JButton btn_actualizarSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jcb_aceptoTerminosCondiciones;
    private javax.swing.JComboBox<String> jcb_estiloLetra;
    private javax.swing.JMenuBar jmb_menuPrincipal;
    private javax.swing.JMenuItem jmi_abrir;
    private javax.swing.JMenu jmi_archivo;
    private javax.swing.JMenuItem jmi_evaluar;
    private javax.swing.JMenu jmi_exportar;
    private javax.swing.JMenuItem jmi_exportarpdf;
    private javax.swing.JMenuItem jmi_guardar;
    private javax.swing.JMenuItem jmi_limpiarpantalla;
    private javax.swing.JPanel jp_examenCanvas;
    private javax.swing.JPanel jp_listar;
    private javax.swing.JPanel jp_miniWord;
    private javax.swing.JRadioButton jrb_for;
    private javax.swing.JRadioButton jrb_todasLasAnteriorires;
    private javax.swing.JRadioButton jrb_while;
    private javax.swing.JLabel lbl_coloBackground;
    private javax.swing.JLabel lbl_colorLetra;
    private javax.swing.JLabel lbl_descripcionExamen;
    private javax.swing.JLabel lbl_estiloLetra;
    private javax.swing.JLabel lbl_ingreseTexto;
    private javax.swing.JLabel lbl_tamanoLetra;
    private javax.swing.JLabel lbl_textoTab1;
    private javax.swing.JLabel lbl_tipoLetra;
    private javax.swing.JTextField txt_contenido;
    private javax.swing.JTextArea txt_justifiquerespuesta;
    private javax.swing.JTextField txt_tamanoLetra;
    private javax.swing.JTextField txt_tipoLetra;
    // End of variables declaration//GEN-END:variables
}
